/**
 * Temporary CYouMedia branding override.
 * Revert this file (and public/brand/cyoudmedia-logo.png) to restore QLIQQI branding.
 */
export const brand = {
  name: "CYouMedia",
  logoSrc: "/brand/cyoudmedia-logo.png",
  logoAspectRatio: 889 / 198,
  /** Shown below the logo when the image does not include a tagline */
  tagline: null as string | null,
  title: "CYouMedia Audit Report",
  description: "Enterprise AI-Visibility & SEO audit by CYouMedia",
  footerCredit: "Generated by CYouMedia",
} as const;
